
import java.io.IOException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OpenDisplay.java
 *
 * Created on Jan 4, 2012, 1:45:51 PM
 */
/**
 *
 * @author Brute Force
 */
public class OpenDisplay extends javax.swing.JFrame {

    ProcessBuilder pb = new ProcessBuilder("C:\\Program Files\\VideoLAN\\VLC\\vlc.exe");
    //ClientStat clstat = new ClientStat();
    
    //EcgDisplay ed = new EcgDisplay();
    
    
    
    
    /** Creates new form OpenDisplay */
    public OpenDisplay()  {
        
         
        initComponents();
        this.setLocationRelativeTo(null);
        
    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EcgButton = new javax.swing.JButton();
        StethoscopeButton = new javax.swing.JButton();
        ColposcopeButton = new javax.swing.JButton();
        MicroscopeButton = new javax.swing.JButton();
        XrayButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EcgButton.setFont(new java.awt.Font("Tahoma", 0, 18));
        EcgButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ECG (320 x 256) (160 x 128).jpg"))); // NOI18N
        EcgButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EcgButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EcgButtonMouseEntered(evt);
            }
        });

        StethoscopeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StethoscopeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Stethoscope.jpg"))); // NOI18N
        StethoscopeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StethoscopeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StethoscopeButtonMouseEntered(evt);
            }
        });

        ColposcopeButton.setFont(new java.awt.Font("Tahoma", 0, 18));
        ColposcopeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/colposcope with image splitter and video camera (199 x 262).jpg"))); // NOI18N
        ColposcopeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ColposcopeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ColposcopeButtonMouseEntered(evt);
            }
        });

        MicroscopeButton.setFont(new java.awt.Font("Tahoma", 0, 18));
        MicroscopeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Microscope.jpg"))); // NOI18N
        MicroscopeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MicroscopeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MicroscopeButtonMouseEntered(evt);
            }
        });

        XrayButton.setFont(new java.awt.Font("Tahoma", 0, 18));
        XrayButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images-x-ray-p2-i5 (186 x 194).jpg"))); // NOI18N
        XrayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XrayButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                XrayButtonMouseEntered(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Department of Biomedical Physics and Technology");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("University Of Dhaka");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel4.setText("Partial Contribution: ");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/farmFresh (85 x 73).jpg"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel6.setText("Developed By:");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 153), null));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24));
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RURAL HEALTH MONITORING SYSTEM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EcgButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ColposcopeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StethoscopeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(MicroscopeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                        .addComponent(XrayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(StethoscopeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(XrayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MicroscopeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EcgButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(ColposcopeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jLabel5)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4)
                            .addGap(35, 35, 35)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EcgButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EcgButtonMouseEntered
        // TODO add your handling code here:
        
        EcgButton.setToolTipText("ECG");
                //showMessage("");
    }//GEN-LAST:event_EcgButtonMouseEntered

    private void StethoscopeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StethoscopeButtonMouseEntered
        // TODO add your handling code here:
        StethoscopeButton.setToolTipText("Stethoscope");
    }//GEN-LAST:event_StethoscopeButtonMouseEntered

    private void ColposcopeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColposcopeButtonMouseEntered
        // TODO add your handling code here:
        ColposcopeButton.setToolTipText("Colposcope");
    }//GEN-LAST:event_ColposcopeButtonMouseEntered

    private void MicroscopeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MicroscopeButtonMouseEntered
        // TODO add your handling code here:
        MicroscopeButton.setToolTipText("Microscope");
        
    }//GEN-LAST:event_MicroscopeButtonMouseEntered

    private void XrayButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XrayButtonMouseEntered
        // TODO add your handling code here:
        XrayButton.setToolTipText("X-ray Viewer");
    }//GEN-LAST:event_XrayButtonMouseEntered

    private void EcgButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EcgButtonMouseClicked
        // TODO add your handling code here:
        try{
        new EcgDisplay().setVisible(true);
        }
        catch (UnknownHostException ex) {
                    Logger.getLogger(EcgDisplay.class.getName()).log(Level.SEVERE, null, ex);
                }
        //this.setVisible(false);
        //this.dispose();
    }//GEN-LAST:event_EcgButtonMouseClicked

    private void ColposcopeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColposcopeButtonMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Connect The Device to PC's USB port and operate using Webcam Software" );
    }//GEN-LAST:event_ColposcopeButtonMouseClicked

    private void MicroscopeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MicroscopeButtonMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Connect The Device to PC's USB port and operate using Webcam Software" );
    }//GEN-LAST:event_MicroscopeButtonMouseClicked

    private void XrayButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XrayButtonMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Connect The Device to PC's USB port and operate using Webcam Software" );
    }//GEN-LAST:event_XrayButtonMouseClicked

    private void StethoscopeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StethoscopeButtonMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Connect Stethoscope and Headphone with PC and go to VLC's Media->Open Capture Device->Capturte Decie the click Play");
        try {
            Process start = pb.start();
        } catch (IOException ex) {
            Logger.getLogger(OpenDisplay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_StethoscopeButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new OpenDisplay().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ColposcopeButton;
    private javax.swing.JButton EcgButton;
    private javax.swing.JButton MicroscopeButton;
    private javax.swing.JButton StethoscopeButton;
    private javax.swing.JButton XrayButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
