
import javax.swing.ImageIcon;




/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginWait.java
 *
 * Created on Jan 20, 2012, 7:38:04 PM
 */
/**
 *
 * @author Aumi
 */
public class LoginWait extends javax.swing.JFrame {

    /** Creates new form LoginWait */
    public LoginWait() {
        ImageIcon img = new ImageIcon("./Info/ecg-icon.png");
        this.setIconImage(img.getImage());
        this.setLocationRelativeTo(null);
        
        initComponents();
        //setLocation(400,200);
        
        
        
    }
    
    
  
   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setTitle("Please Wait ");
        setAlwaysOnTop(true);
        setName("LoginWait"); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loading_transparent (1).gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel1)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LoginWait().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
